services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: owidimporter:latest
    container_name: owidimporter
    network_mode: host
    # ports:
    #   - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped